// Liber Operationis — 真实可用的神秘学参考数据
// 取材均为公共领域：Agrippa《De Occulta Philosophia》、Lemegeton、Sepher Yetzirah、
// Picatrix、Corpus Hermeticum、Golden Dawn 公开材料

const LIBER = {
  // 章节
  toc: [
    { id: "praefatio",    num: "",     latin: "Praefatio",            zh: "卷首与体例",     part: "" },
    { id: "hermetica",    num: "I",    latin: "Corpus Hermeticum",    zh: "赫密士文集",     part: "Pars Prima · 哲学" },
    { id: "elementa",     num: "II",   latin: "De Elementis",         zh: "四元素与三本原", part: "Pars Prima · 哲学" },
    { id: "kabbalah",     num: "III",  latin: "Arbor Sephirothica",   zh: "卡巴拉与生命之树", part: "Pars Secunda · 宇宙" },
    { id: "astrologia",   num: "IV",   latin: "Astrologia",           zh: "占星基本对应",   part: "Pars Secunda · 宇宙" },
    { id: "planetae",     num: "V",    latin: "De Planetis",          zh: "七曜行星魔法",   part: "Pars Tertia · 实修" },
    { id: "horae",        num: "VI",   latin: "Horae Planetariae",    zh: "行星时计算",     part: "Pars Tertia · 实修", tool: true },
    { id: "tarot",        num: "VII",  latin: "Tarocchi",             zh: "塔罗与赫布来字母", part: "Pars Tertia · 实修" },
    { id: "divinatio",    num: "VIII", latin: "Divinatio",            zh: "塔罗占卜",       part: "Pars Tertia · 实修", tool: true },
    { id: "goetia",       num: "IX",   latin: "Ars Goetia",           zh: "所罗门钥匙之灵", part: "Pars Quarta · 仪轨" },
    { id: "rituale",      num: "X",    latin: "Rituale Pentagrammi",  zh: "小五芒星驱逐仪", part: "Pars Quarta · 仪轨" },
    { id: "alchemia",     num: "XI",   latin: "Tabula Smaragdina",    zh: "翠玉录与炼金大业", part: "Pars Quarta · 仪轨" },
    { id: "tabulae",      num: "XII",  latin: "Tabulae Correspondentiarum", zh: "对应表汇编", part: "Pars Quinta · 附录" },
    { id: "bibliographia",num: "XIII", latin: "Bibliographia",        zh: "书目与原典指引", part: "Pars Quinta · 附录" },
  ],

  // 古典七星 — 来自 Agrippa Book II 详细记载
  planets: [
    { id: "saturn",  glyph: "♄", latin: "Saturnus",  zh: "土星", day: "Saturni",   dayZh: "土曜（星期六）",
      hebrew: "שבתאי", angel: "Cassiel",   intel: "Agiel",       spirit: "Zazel",
      metal: "铅 Plumbum", color: "黑 / 深紫", number: 3, kameaSum: 15,
      incense: "没药、安息香、柏",   stone: "缟玛瑙、黑曜石、蓝宝石",
      herb: "天仙子、毒参、附子",   animal: "山羊、乌鸦、鼹鼠",
      psalm: "诗篇 §35",
      virtues: "时间、限制、纪律、土地、农耕、年长、终结、孤独、稳固、骨骼。",
      hours: "宜立约、研究深奥、土地与建筑事；忌新发起、婚事、旅行。" },

    { id: "jupiter", glyph: "♃", latin: "Iuppiter",  zh: "木星", day: "Iovis",     dayZh: "木曜（星期四）",
      hebrew: "צדק", angel: "Sachiel",    intel: "Iophiel",     spirit: "Hismael",
      metal: "锡 Stannum", color: "蓝、紫、王者绛红", number: 4, kameaSum: 34,
      incense: "雪松、肉豆蔻、藏红花", stone: "紫水晶、青金石、黄玉",
      herb: "鼠尾草、樱桃、橡树",     animal: "鹰、独角兽、孔雀",
      psalm: "诗篇 §23",
      virtues: "扩张、慷慨、荣誉、合法、丰盛、君权、宗教、祝福、肝脏。",
      hours: "宜签约、求职晋升、和解、典礼；忌缩减、清算之事。" },

    { id: "mars",    glyph: "♂", latin: "Mars",      zh: "火星", day: "Martis",    dayZh: "火曜（星期二）",
      hebrew: "מאדים", angel: "Samael",   intel: "Graphiel",    spirit: "Bartzabel",
      metal: "铁 Ferrum",  color: "猩红、铁锈红", number: 5, kameaSum: 65,
      incense: "龙血、烟草、辣椒",   stone: "红宝石、赤铁矿、红玛瑙",
      herb: "荨麻、生姜、大蒜",     animal: "狼、马、啄木鸟",
      psalm: "诗篇 §6",
      virtues: "勇气、外科、战斗、切割、纪律、铁器、肌肉、热血。",
      hours: "宜外科、护身、训练；忌契约、调和、谈判。" },

    { id: "sol",     glyph: "☉", latin: "Sol",       zh: "太阳", day: "Solis",     dayZh: "日曜（星期日）",
      hebrew: "שמש",   angel: "Michael",  intel: "Nakhiel",     spirit: "Sorath",
      metal: "金 Aurum",   color: "金、橙黄", number: 6, kameaSum: 111,
      incense: "乳香、肉桂、月桂、没药金", stone: "黄水晶、托帕石、钻石",
      herb: "向日葵、月桂、藏红花、橙",   animal: "狮、雄鸡、天鹅",
      psalm: "诗篇 §19",
      virtues: "中心、王权、健康、显赫、辉光、心脏、生命力。",
      hours: "宜朝见君上、显达事、康复、立誓；为日中之冠。" },

    { id: "venus",   glyph: "♀", latin: "Venus",     zh: "金星", day: "Veneris",   dayZh: "金曜（星期五）",
      hebrew: "נוגה",  angel: "Anael",    intel: "Hagiel",      spirit: "Kedemel",
      metal: "铜 Cuprum",  color: "翠绿、玫瑰", number: 7, kameaSum: 175,
      incense: "玫瑰、檀香、苹果花、安息香", stone: "祖母绿、孔雀石、玫瑰石英",
      herb: "玫瑰、桃金娘、马鞭草、苹果",   animal: "鸽、麻雀、天鹅",
      psalm: "诗篇 §45",
      virtues: "和合、艺术、美、丰饶、爱欲、外交、肾脏。",
      hours: "宜求爱、艺术、和解、签订姻缘；忌硬性争斗。" },

    { id: "mercury", glyph: "☿", latin: "Mercurius", zh: "水星", day: "Mercurii",  dayZh: "水曜（星期三）",
      hebrew: "כוכב", angel: "Raphael",   intel: "Tiriel",      spirit: "Taphthartharath",
      metal: "汞 Hydrargyrum", color: "杂色、橙、蓝灰", number: 8, kameaSum: 260,
      incense: "薰衣草、薄荷、白檀、苦艾",  stone: "玛瑙、橄榄石、青金石",
      herb: "薄荷、莳萝、蕨、马齿苋",       animal: "狐、燕、猴、朱鹭",
      psalm: "诗篇 §8",
      virtues: "信使、词语、商贸、巧术、医术、神经、肺。",
      hours: "宜书写、合同、出行、占卜、学习；忌孤注一掷之事。" },

    { id: "luna",    glyph: "☽", latin: "Luna",      zh: "月亮", day: "Lunae",     dayZh: "月曜（星期一）",
      hebrew: "לבנה", angel: "Gabriel",   intel: "Malka be Tarshishim", spirit: "Hasmodai",
      metal: "银 Argentum", color: "银、灰白、海蓝", number: 9, kameaSum: 369,
      incense: "茉莉、白檀、樟脑、海藻", stone: "月光石、珍珠、海蓝宝、银",
      herb: "白百合、罂粟、瓜、柳",     animal: "鹿、犬、蛙、夜枭",
      psalm: "诗篇 §81",
      virtues: "梦境、潮汐、孕育、阴影、记忆、消化、肾上腺。",
      hours: "宜旅行、占梦、清洁仪、求孕；勿在新月与月蚀行强法。" },
  ],

  // 行星时序 — 加迪安按日（Chaldean order in calculator）
  // 古典对应 (七天每天的行星统治者)
  dayRulers: ["sol","luna","mars","mercury","jupiter","venus","saturn"], // Sun..Sat
  // 行星时的迦勒底序 (Saturn..Moon by speed/distance, descending)
  chaldeanOrder: ["saturn","jupiter","mars","sol","venus","mercury","luna"],

  // 四元素 + 三原 (硫磺、汞、盐)
  elementa: [
    { id: "ignis",  glyph: "🜂", latin: "Ignis",  zh: "火", quality: "热·干", direction: "南", season: "夏", humor: "黄胆汁",
      arch: "Michael", king: "Djin",      tri: "Aries · Leo · Sagittarius",  use: "意志、热情、净化、行动" },
    { id: "aqua",   glyph: "🜄", latin: "Aqua",   zh: "水", quality: "冷·湿", direction: "西", season: "秋", humor: "黏液",
      arch: "Gabriel", king: "Nichsa",    tri: "Cancer · Scorpio · Pisces",  use: "情感、爱、潜意识、洁净" },
    { id: "aer",    glyph: "🜁", latin: "Aer",    zh: "气", quality: "热·湿", direction: "东", season: "春", humor: "血液",
      arch: "Raphael", king: "Paralda",   tri: "Gemini · Libra · Aquarius",  use: "思想、言辞、风、信使" },
    { id: "terra",  glyph: "🜃", latin: "Terra",  zh: "土", quality: "冷·干", direction: "北", season: "冬", humor: "黑胆汁",
      arch: "Auriel",  king: "Ghob",      tri: "Taurus · Virgo · Capricorn", use: "肉身、丰饶、稳固、显化" },
  ],

  tria_prima: [
    { id: "sulphur", glyph: "🜍", latin: "Sulphur",     zh: "硫",   sense: "灵 · 主动 · 燃烧之原" },
    { id: "mercury", glyph: "☿",  latin: "Mercurius",   zh: "汞",   sense: "魂 · 流动 · 居间之原" },
    { id: "sal",     glyph: "🜔", latin: "Sal",         zh: "盐",   sense: "体 · 被动 · 凝固之原" },
  ],

  // 卡巴拉生命之树
  sephiroth: [
    { n:1,  he:"כתר",    latin:"Kether",     zh:"王冠",   meaning:"至高之冠 / 神之意志",
      god:"Eheieh",       arch:"Metatron",  order:"Chaioth ha-Qadesh / 圣兽",
      planet:"原动天 Primum Mobile", color:"白光", body:"颅顶" },
    { n:2,  he:"חכמה",   latin:"Chokmah",    zh:"智慧",   meaning:"原始男性 · 父",
      god:"Yah",          arch:"Raziel",    order:"Auphanim / 轮",
      planet:"恒星天 Zodiacus",       color:"灰", body:"右脑" },
    { n:3,  he:"בינה",   latin:"Binah",      zh:"理解",   meaning:"原始女性 · 母",
      god:"YHVH Elohim",  arch:"Tzaphkiel", order:"Aralim / 大能者",
      planet:"♄ 土星",                 color:"黑", body:"左脑" },
    { n:4,  he:"חסד",    latin:"Chesed",     zh:"慈悲",   meaning:"扩展之爱",
      god:"El",           arch:"Tzadkiel",  order:"Chasmalim / 灿烂者",
      planet:"♃ 木星",                 color:"蓝", body:"右臂" },
    { n:5,  he:"גבורה",  latin:"Geburah",    zh:"严厉",   meaning:"正义之火",
      god:"Elohim Gibor", arch:"Khamael",   order:"Seraphim / 炽天使",
      planet:"♂ 火星",                 color:"红", body:"左臂" },
    { n:6,  he:"תפארת",  latin:"Tiphareth",  zh:"美 · 和谐", meaning:"中心 / 弥赛亚",
      god:"YHVH Eloah ve-Daath", arch:"Raphael", order:"Malachim / 国王",
      planet:"☉ 太阳",                 color:"金黄", body:"心" },
    { n:7,  he:"נצח",    latin:"Netzach",    zh:"胜利",   meaning:"情感 / 自然之爱",
      god:"YHVH Tzabaoth", arch:"Haniel",   order:"Elohim / 神性",
      planet:"♀ 金星",                 color:"翠绿", body:"右髋" },
    { n:8,  he:"הוד",    latin:"Hod",        zh:"辉煌",   meaning:"理智 / 形式",
      god:"Elohim Tzabaoth", arch:"Michael", order:"Beni Elohim / 神子",
      planet:"☿ 水星",                 color:"橙", body:"左髋" },
    { n:9,  he:"יסוד",   latin:"Yesod",      zh:"基础",   meaning:"潜意识 / 月之府",
      god:"Shaddai El Chai", arch:"Gabriel", order:"Cherubim / 智天使",
      planet:"☽ 月亮",                 color:"紫", body:"生殖" },
    { n:10, he:"מלכות",  latin:"Malkuth",    zh:"王国",   meaning:"物质界 · 新娘",
      god:"Adonai ha-Aretz", arch:"Sandalphon", order:"Ishim / 灵魂之火",
      planet:"⊕ 元素界",                color:"四色：橄榄·赤褐·黄褐·黑", body:"双足" },
  ],

  // 黄道十二宫 + 占星基本盘对应
  zodiac: [
    { id:"aries",       glyph:"♈", zh:"白羊", latin:"Aries",       date:"3.21–4.19", el:"火", mode:"基本", ruler:"♂", exalt:"☉", body:"头",     archetype:"启动 / 战士" },
    { id:"taurus",      glyph:"♉", zh:"金牛", latin:"Taurus",      date:"4.20–5.20", el:"土", mode:"固定", ruler:"♀", exalt:"☽", body:"颈",     archetype:"积聚 / 园丁" },
    { id:"gemini",      glyph:"♊", zh:"双子", latin:"Gemini",      date:"5.21–6.20", el:"气", mode:"变动", ruler:"☿", exalt:"—", body:"肩肺",   archetype:"沟通 / 信使" },
    { id:"cancer",      glyph:"♋", zh:"巨蟹", latin:"Cancer",      date:"6.21–7.22", el:"水", mode:"基本", ruler:"☽", exalt:"♃", body:"胸胃",   archetype:"养育 / 母" },
    { id:"leo",         glyph:"♌", zh:"狮子", latin:"Leo",         date:"7.23–8.22", el:"火", mode:"固定", ruler:"☉", exalt:"—", body:"心背",   archetype:"显赫 / 王" },
    { id:"virgo",       glyph:"♍", zh:"处女", latin:"Virgo",       date:"8.23–9.22", el:"土", mode:"变动", ruler:"☿", exalt:"☿", body:"腹肠",   archetype:"分辨 / 工匠" },
    { id:"libra",       glyph:"♎", zh:"天秤", latin:"Libra",       date:"9.23–10.22",el:"气", mode:"基本", ruler:"♀", exalt:"♄", body:"腰肾",   archetype:"权衡 / 调停" },
    { id:"scorpio",     glyph:"♏", zh:"天蝎", latin:"Scorpius",    date:"10.23–11.21",el:"水",mode:"固定", ruler:"♂(♇)", exalt:"—", body:"生殖",  archetype:"转化 / 巫" },
    { id:"sagittarius", glyph:"♐", zh:"射手", latin:"Sagittarius", date:"11.22–12.21",el:"火",mode:"变动", ruler:"♃", exalt:"—", body:"髋腿",   archetype:"远行 / 哲学家" },
    { id:"capricorn",   glyph:"♑", zh:"摩羯", latin:"Capricornus", date:"12.22–1.19",el:"土", mode:"基本", ruler:"♄", exalt:"♂", body:"膝骨",   archetype:"成就 / 隐士" },
    { id:"aquarius",    glyph:"♒", zh:"水瓶", latin:"Aquarius",    date:"1.20–2.18", el:"气", mode:"固定", ruler:"♄(♅)", exalt:"—", body:"踝循环", archetype:"理想 / 革命者" },
    { id:"pisces",      glyph:"♓", zh:"双鱼", latin:"Pisces",      date:"2.19–3.20", el:"水", mode:"变动", ruler:"♃(♆)", exalt:"♀", body:"足",    archetype:"溶解 / 神秘者" },
  ],

  // 行星宫位主管表
  houses: [
    {n:1,  zh:"命宫",   latin:"Vita",         theme:"自我 / 身体 / 出场"},
    {n:2,  zh:"财帛宫", latin:"Lucrum",       theme:"价值 / 资源 / 个人财"},
    {n:3,  zh:"兄弟宫", latin:"Fratres",      theme:"言语 / 短行 / 学习"},
    {n:4,  zh:"田宅宫", latin:"Genitor",      theme:"家庭 / 根源 / 终结"},
    {n:5,  zh:"子女宫", latin:"Nati",         theme:"创造 / 子女 / 游戏"},
    {n:6,  zh:"奴仆宫", latin:"Valetudo",     theme:"健康 / 工作 / 服务"},
    {n:7,  zh:"夫妻宫", latin:"Uxor",         theme:"对方 / 婚姻 / 公开敌"},
    {n:8,  zh:"疾厄宫", latin:"Mors",         theme:"共有资源 / 死亡 / 转化"},
    {n:9,  zh:"迁移宫", latin:"Pietas",       theme:"长行 / 信仰 / 高等学问"},
    {n:10, zh:"官禄宫", latin:"Regnum",       theme:"事业 / 名声 / 母"},
    {n:11, zh:"福德宫", latin:"Benefacta",    theme:"友 / 团体 / 愿望"},
    {n:12, zh:"玄秘宫", latin:"Carcer",       theme:"隐秘 / 潜意识 / 自伤" },
  ],

  // 大阿卡纳 22 张 + 黄金黎明 / 卡巴拉对应
  arcana: [
    { n:0,  rom:"0",     latin:"Stultus",        zh:"愚者",     he:"א", letter:"Aleph",  attr:"气 🜁", path:"11 Kether→Chokmah" },
    { n:1,  rom:"I",     latin:"Magus",          zh:"魔术师",   he:"ב", letter:"Beth",   attr:"☿",     path:"12 Kether→Binah" },
    { n:2,  rom:"II",    latin:"Sacerdotissa",   zh:"女祭司",   he:"ג", letter:"Gimel",  attr:"☽",     path:"13 Kether→Tiphareth" },
    { n:3,  rom:"III",   latin:"Imperatrix",     zh:"皇后",     he:"ד", letter:"Daleth", attr:"♀",     path:"14 Chokmah→Binah" },
    { n:4,  rom:"IV",    latin:"Imperator",      zh:"皇帝",     he:"ה", letter:"Heh",    attr:"♈",     path:"15 Chokmah→Tiphareth" },
    { n:5,  rom:"V",     latin:"Hierophanta",    zh:"教皇",     he:"ו", letter:"Vav",    attr:"♉",     path:"16 Chokmah→Chesed" },
    { n:6,  rom:"VI",    latin:"Amantes",        zh:"恋人",     he:"ז", letter:"Zayin",  attr:"♊",     path:"17 Binah→Tiphareth" },
    { n:7,  rom:"VII",   latin:"Currus",         zh:"战车",     he:"ח", letter:"Cheth",  attr:"♋",     path:"18 Binah→Geburah" },
    { n:8,  rom:"VIII",  latin:"Fortitudo",      zh:"力量",     he:"ט", letter:"Teth",   attr:"♌",     path:"19 Chesed→Geburah" },
    { n:9,  rom:"IX",    latin:"Eremita",        zh:"隐者",     he:"י", letter:"Yod",    attr:"♍",     path:"20 Chesed→Tiphareth" },
    { n:10, rom:"X",     latin:"Rota Fortunae",  zh:"命运之轮", he:"כ", letter:"Kaph",   attr:"♃",     path:"21 Chesed→Netzach" },
    { n:11, rom:"XI",    latin:"Iustitia",       zh:"正义",     he:"ל", letter:"Lamed",  attr:"♎",     path:"22 Geburah→Tiphareth" },
    { n:12, rom:"XII",   latin:"Suspensus",      zh:"倒吊人",   he:"מ", letter:"Mem",    attr:"水 🜄",  path:"23 Geburah→Hod" },
    { n:13, rom:"XIII",  latin:"Mors",           zh:"死神",     he:"נ", letter:"Nun",    attr:"♏",     path:"24 Tiphareth→Netzach" },
    { n:14, rom:"XIV",   latin:"Temperantia",    zh:"节制",     he:"ס", letter:"Samekh", attr:"♐",     path:"25 Tiphareth→Yesod" },
    { n:15, rom:"XV",    latin:"Diabolus",       zh:"恶魔",     he:"ע", letter:"Ayin",   attr:"♑",     path:"26 Tiphareth→Hod" },
    { n:16, rom:"XVI",   latin:"Turris",         zh:"塔",       he:"פ", letter:"Peh",    attr:"♂",     path:"27 Netzach→Hod" },
    { n:17, rom:"XVII",  latin:"Stellae",        zh:"星",       he:"צ", letter:"Tzaddi", attr:"♒",     path:"28 Netzach→Yesod" },
    { n:18, rom:"XVIII", latin:"Luna",           zh:"月",       he:"ק", letter:"Qoph",   attr:"♓",     path:"29 Netzach→Malkuth" },
    { n:19, rom:"XIX",   latin:"Sol",            zh:"太阳",     he:"ר", letter:"Resh",   attr:"☉",     path:"30 Hod→Yesod" },
    { n:20, rom:"XX",    latin:"Iudicium",       zh:"审判",     he:"ש", letter:"Shin",   attr:"火 🜂",  path:"31 Hod→Malkuth" },
    { n:21, rom:"XXI",   latin:"Mundus",         zh:"世界",     he:"ת", letter:"Tav",    attr:"♄ / 土", path:"32 Yesod→Malkuth" },
  ],

  // 塔罗 — 上下含义
  arcanaMeaning: {
    0:  ["新起点 · 跃入未知 · 信任", "鲁莽 · 草率 · 拒绝承诺"],
    1:  ["意志 · 集中 · 化念为实", "操弄 · 才能误用"],
    2:  ["内在直觉 · 静默 · 隐密知识", "隐藏的真相 · 表面知性"],
    3:  ["丰饶 · 创造力 · 母性", "停滞 · 创造受阻"],
    4:  ["权威 · 结构 · 父性", "僵化 · 滥用权力"],
    5:  ["传统 · 教导 · 灵性团体", "制度束缚 · 教条"],
    6:  ["契合 · 选择 · 联合", "失谐 · 价值冲突"],
    7:  ["意志驱进 · 控制 · 凯旋", "冲撞 · 失控"],
    8:  ["内在勇气 · 慈柔之力", "怯弱 · 力之滥用"],
    9:  ["独处 · 内省 · 引路灯", "孤立 · 退缩"],
    10: ["命运转折 · 周期 · 机运", "逆运 · 抗拒变化"],
    11: ["平衡 · 真相 · 因果", "失衡 · 偏私"],
    12: ["视角颠倒 · 暂悬 · 牺牲", "无谓牺牲 · 拒绝放手"],
    13: ["终结 · 蜕变 · 必然", "拒绝放下 · 停滞"],
    14: ["调和 · 融合 · 中道", "过度 · 失衡"],
    15: ["束缚 · 物欲 · 影子", "解开锁链 · 觉察"],
    16: ["突变 · 启示 · 旧结构崩塌", "幸免 · 推迟之变"],
    17: ["希望 · 启灵 · 平和", "失望 · 信念动摇"],
    18: ["梦境 · 幻象 · 潜意识汹涌", "迷惑澄清 · 直面恐惧"],
    19: ["明亮 · 喜悦 · 成就", "短暂的乌云"],
    20: ["觉醒 · 召命 · 复活", "拒绝召唤"],
    21: ["完成 · 整合 · 圆满", "未竟 · 止于一步之遥"],
  },

  // 所罗门 72 灵 — 选取主要 12 位 (含完整称号、军团、权能、印象、时辰、神名)
  goetia: [
    { rank:1,  name:"Bael",        title:"国王 Rex",        legions:66,  power:"授隐身术，统御东方。", form:"猫·人·蟾蜍三首之像。", divine:"Adonai" },
    { rank:2,  name:"Agares",      title:"公爵 Dux",        legions:31,  power:"使逃者归来；教各种语言；震地。", form:"骑鳄之老者，臂上立鹰。", divine:"Onaim" },
    { rank:3,  name:"Vassago",     title:"君主 Princeps",   legions:26,  power:"言过去未来，寻找失物。", form:"性温和，属善灵。", divine:"Adonai" },
    { rank:5,  name:"Marbas",      title:"总裁 Praeses",    legions:36,  power:"揭隐秘，治愈疾病，授机巧之术。", form:"狮，应召化为人形。", divine:"YHVH" },
    { rank:9,  name:"Paimon",      title:"国王 Rex",        legions:200, power:"教一切艺术与隐秘哲学，授予通晓神圣事。", form:"戴宝冠之男子骑骆驼，先有号角声。", divine:"Adonai" },
    { rank:11, name:"Gusion",      title:"公爵 Dux",        legions:40,  power:"判过去现在未来；和解仇人。", form:"如鬼鬼祟祟之人。", divine:"YHVH" },
    { rank:32, name:"Asmoday",     title:"国王 Rex",        legions:72,  power:"授算术、几何、天文、机械；指示宝藏。", form:"三首：牛·人·羊；足如鹅；持矛与旗。", divine:"AHIH" },
    { rank:35, name:"Marchosias",  title:"侯爵 Marchio",    legions:30,  power:"为召唤者强力作战；忠于己誓。", form:"母狼带翼，蛇尾，吐火。", divine:"YHVH" },
    { rank:45, name:"Vine",        title:"国王伯爵",         legions:36,  power:"揭巫术，识隐者，造塔倾墙，知未来。", form:"狮持蛇骑黑马。", divine:"AHIH" },
    { rank:56, name:"Gremory",     title:"公爵 Dux",        legions:26,  power:"言过去现在未来，寻宝藏，使爱。", form:"骑骆驼之美妇人，腰束公爵冠。", divine:"YHVH" },
    { rank:68, name:"Belial",      title:"国王 Rex",        legions:80,  power:"授官位与友谊，需供以献礼。", form:"乘火车之美丽天使。", divine:"AHIH IHVH" },
    { rank:72, name:"Andromalius", title:"伯爵 Comes",      legions:36,  power:"擒贼追赃；惩处不义；揭隐藏之物。", form:"持大蛇之男子。", divine:"AHIH" },
  ],

  // 翠玉录 (公共领域 / 牛顿英译之常见中译)
  emerald: [
    "真实不虚，确凿无疑，最真之实。",
    "下者如同上者，上者如同下者；以此成就独一之奇迹。",
    "万物本于独一，经独一之冥思而生；故万物皆由此独一，经化育而出。",
    "其父为日，其母为月；风承之于其腹，地为之乳母。",
    "此乃举世之全能之父；其能完整，若化为地。",
    "汝当以巧分土于火，分细于粗，缓而精审。",
    "其升自地而至天，复降于地，纳上下之力。",
    "由此汝得举世之荣耀；一切晦暗将自汝远遁。",
    "此为强中之强，能胜万物精微，能透坚固之物。",
    "世界即此而造。由此万象奇变，皆依此道。",
    "故吾名曰赫密士·三重伟大者，备具三部之哲学。",
    "凡吾所言关于太阳之造作者，至此尽矣。",
  ],

  // 炼金大业
  opus: [
    { id:"calcinatio", lat:"Calcinatio",  zh:"煅烧", color:"黑", phase:"Nigredo I",  desc:"以火焚之至灰。烧尽外形与执念。" },
    { id:"solutio",    lat:"Solutio",     zh:"溶解", color:"黑", phase:"Nigredo II", desc:"以水溶之。情感与潜意识浮起。" },
    { id:"separatio",  lat:"Separatio",   zh:"分离", color:"灰", phase:"Albedo I",   desc:"分粗与精，善与恶。" },
    { id:"coniunctio", lat:"Coniunctio",  zh:"结合", color:"白", phase:"Albedo II",  desc:"对立调和。神圣婚姻之初。" },
    { id:"fermentatio",lat:"Fermentatio", zh:"发酵", color:"白→金", phase:"Citrinitas", desc:"灵入死物，使之复活。" },
    { id:"distillatio",lat:"Distillatio", zh:"蒸馏", color:"金", phase:"Rubedo I",   desc:"反复升降，提炼精华。" },
    { id:"coagulatio", lat:"Coagulatio",  zh:"凝合", color:"红", phase:"Rubedo II",  desc:"圣石成形。Solve et Coagula 之终。" },
  ],

  // 小五芒星驱逐仪 LBRP — 完整步骤 (Golden Dawn 公开材料)
  lbrp: [
    { step:"i",   title:"卡巴拉十字 · Qabbalistic Cross",
      action:"面东而立。右手食指轻触额头，唱：Atah（汝之）。下移至胸下，唱：Malkuth（王国）。触右肩，唱：ve-Geburah（与力）。触左肩，唱：ve-Gedulah（与荣）。双手于胸前合掌，唱：le-Olahm, Amen（直至永远，阿门）。" },
    { step:"ii",  title:"画驱逐五芒星 · 东方 (土)",
      action:"以右手食指或仪式匕，自左下角始画地之驱逐五芒星。中心而向东，以全力震动神名：YOD-HEH-VAV-HEH (יהוה)。" },
    { step:"iii", title:"画 · 南方",
      action:"持气于指尖，转身面南。复画驱逐五芒星，中心而向南，震动：ADONAI (אדני)。" },
    { step:"iv",  title:"画 · 西方",
      action:"转身面西。画驱逐五芒星，中心而向西，震动：EHEIEH (אהיה)。" },
    { step:"v",   title:"画 · 北方",
      action:"转身面北。画驱逐五芒星，中心而向北，震动：AGLA (אגלא)，即 Atah Gibor le-Olahm Adonai 之缩。" },
    { step:"vi",  title:"召请四大天使",
      action:"复回东方。展双臂作十字。唱：在我之前 RAPHAEL（气之天使）；在我之后 GABRIEL（水）；在我之右 MICHAEL（火）；在我之左 AURIEL（土）。胸前燃六芒星，环绕我者乃五芒星之火焰。" },
    { step:"vii", title:"复作卡巴拉十字 · 收圈",
      action:"再行第一步，以平衡气场，作结。" },
  ],
};

window.LIBER = LIBER;
